# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/demo2/Basys3_Master.xdc

# IP: ip/KeyboardCtrl_1/KeyboardCtrl_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==KeyboardCtrl_1 || ORIG_REF_NAME==KeyboardCtrl_1} -quiet] -quiet

# IP: ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_7 || ORIG_REF_NAME==blk_mem_gen_7} -quiet] -quiet

# IP: ip/blk_mem_gen_6_1/blk_mem_gen_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_6 || ORIG_REF_NAME==blk_mem_gen_6} -quiet] -quiet

# IP: ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_5 || ORIG_REF_NAME==blk_mem_gen_5} -quiet] -quiet

# IP: ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_4 || ORIG_REF_NAME==blk_mem_gen_4} -quiet] -quiet

# IP: ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_3 || ORIG_REF_NAME==blk_mem_gen_3} -quiet] -quiet

# IP: ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc

# XDC: ip/blk_mem_gen_6_1/blk_mem_gen_6_ooc.xdc

# XDC: ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc

# XDC: ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc

# XDC: ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc

# XDC: ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
