# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yoyolee118/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/yoyolee118/project_3/project_3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/yoyolee118/project_3/project_3.ip_user_files/ip_keyboard [current_project]
set_property ip_output_repo c:/Users/yoyolee118/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/yoyolee118/project_3/p-green.coe
add_files C:/Users/yoyolee118/project_3/doodleL.coe
add_files C:/Users/yoyolee118/project_3/bullet.coe
add_files C:/Users/yoyolee118/project_3/monster0.coe
add_files C:/Users/yoyolee118/project_3/press_enter.coe
add_files C:/Users/yoyolee118/project_3/jump.coe
add_files C:/Users/yoyolee118/project_3/lose.coe
add_files C:/Users/yoyolee118/project_3/win.coe
read_verilog -library xil_defaultlib C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/new/tt.v
read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/KeyboardCtrl_1/KeyboardCtrl_1.xci

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_6_1/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_6_1/blk_mem_gen_6_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yoyolee118/project_3/project_3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yoyolee118/project_3/project_3.srcs/constrs_1/imports/demo2/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/yoyolee118/project_3/project_3.srcs/constrs_1/imports/demo2/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1 -directive RuntimeOptimized


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
